import type { CaseRecord } from "./types";

function formatDate(iso: string | undefined): string {
  if (!iso) return "an unspecified date";
  return iso;
}

export function generateDemandLetter(caseRecord: CaseRecord): {
  letter: string;
  reviewItems: string[];
} {
  const { clientName, intake, extraction, owner } = caseRecord;
  const v = intake.values;
  const today = new Date().toISOString().slice(0, 10);

  const chronologyLines = extraction.chronology.length
    ? extraction.chronology
        .map((e) => `  - ${e.date} — ${e.provider}: ${e.summary}`)
        .join("\n")
    : "  [No chronology on file yet — run document extraction first.]";

  const first = extraction.chronology[0];
  const last = extraction.chronology[extraction.chronology.length - 1];

  const letter = `RE: Demand for Settlement — ${clientName}
Incident date: ${formatDate(v.incidentDate)}
Prepared by: ${owner} · Casewire (prototype — not a real firm)
Date drafted: ${today}

To Whom It May Concern:

This office represents ${clientName} in connection with injuries sustained on ${formatDate(
    v.incidentDate
  )}. ${v.liability ?? "[Liability narrative pending — complete intake.]"}

INJURIES AND TREATMENT

${clientName} sustained the following injuries: ${
    v.injurySeverity ?? "[Injury detail pending — complete intake.]"
  } ${v.treatmentStatus ? `Regarding ongoing care: ${v.treatmentStatus}` : ""}

Medical treatment chronology${
    first && last ? ` (${first.date} through ${last.date})` : ""
  }:
${chronologyLines}

DAMAGES

Based on the chronology above, ${clientName} has ${
    extraction.chronology.length
  } documented medical encounter${
    extraction.chronology.length === 1 ? "" : "s"
  } on file. Itemized medical billing, wage-loss documentation, and a final damages figure are not yet attached and must be added before this letter is sent.

We look forward to a prompt response and resolution of this matter.

Sincerely,
${owner}
Casewire — connected case prototype`;

  const reviewItems = [
    ...extraction.flags.map((f) => f.message),
    "Attach itemized medical billing and a final damages figure — not generated by this prototype.",
    ...(v.priorRepresentation && /yes|yeah|yep/i.test(v.priorRepresentation)
      ? [
          "Client indicated prior contact with another attorney — confirm there is no conflicting representation before sending.",
        ]
      : []),
    ...(extraction.chronology.length === 0
      ? ["No chronology on file — run document extraction before sending."]
      : []),
  ];

  return { letter, reviewItems };
}
